### PR TITLE
Fix return value for op_open

### PR DESCRIPTION
**Pull request by jgavris**
Bazel pointed this one out

### CODE REVIEW

**Review by rjschnei — APPROVED** [review]

**Comment by jgavris** [comment]
Would like a linux guy to test this ... seems innocent

**Comment by jgavris** [comment]
@jpeabodyjr you could test this out by running https://github.com/ButterflyNetwork/software/pull/2476

**Comment by jpeabodyjr** [comment]
@jgavris I'll test this out this morning.

**Comment by jpeabodyjr** [comment]
I ran some things through BniProbeTester and also ran ImagingSandbox. GTG

**Review by jpeabodyjr — APPROVED** [review]
:shipit:

**Comment by jgavris** [comment]
Thanks!

**Pull request merged**
